spring:
  application:
    name: BankStarApplication
  main:
    allow-bean-definition-overriding: true

  # H2 (Read-Only)
  datasource:
    url: jdbc:h2:file:${user.dir}/transaction;ACCESS_MODE_DATA=r;DB_CLOSE_DELAY=-1;IFEXISTS=TRUE
    driver-class-name: org.h2.Driver
    username:
    password:
    hikari:
      read-only: true
      pool-name: H2-Pool
      maximum-pool-size: 3

  # PostgreSQL (Read-Write)
  postgresql:
    datasource:
      url: jdbc:postgresql://localhost:5432/recommendations
      username: student
      password: chocolatefrog
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: HikariPool-PostgreSQL
        maximum-pool-size: 5

  # Liquibase (применяется к PostgreSQL)
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    url: ${spring.postgresql.datasource.url}
    user: ${spring.postgresql.datasource.username}
    password: ${spring.postgresql.datasource.password}

  # JPA (отключаем авто-DDL, т.к. используем Liquibase)
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        enable_lazy_load_no_trans: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# Доп. настройки
app:
  validate-h2-schema: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    logging:
      level:
        liquibase: DEBUG
      logging:
          level:
            org.hibernate.SQL: DEBUG
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE